-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    fullName VARCHAR(100) NOT NULL
);

-- Create todos table
CREATE TABLE IF NOT EXISTS todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(2000),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    createdDate TIMESTAMP NOT NULL,
    completedDate TIMESTAMP,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_todo_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create index on username for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Create index on user_id for faster todo queries
CREATE INDEX IF NOT EXISTS idx_todos_user_id ON todos(user_id);

-- Insert default users if they don't exist
INSERT INTO users (username, password, email, fullName) 
SELECT 'admin', 'admin123', 'admin@example.com', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

INSERT INTO users (username, password, email, fullName) 
SELECT 'user1', 'user123', 'user1@example.com', 'User One'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'user1');

INSERT INTO users (username, password, email, fullName) 
SELECT 'user2', 'user123', 'user2@example.com', 'User Two'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'user2');

